# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2553b955a4693aaa303ee38c67d8d709d5ab669ac7a287411afc168b49f265591b9d733fd72de1755bc14c97bd16e14b79bd35ad0fc02b8d6a6a244b5c9e13af

test:
  secret_key_base: 83ea633036e0fd6d2e36fcd1b2ea8c1b3301f461a4200d936f82fa612a7f11a6d950b17913dbabd85d97d78ea3e64d4226f64911f9c4d6619cfbe4a752888499

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
